wallpaper = ~/.local/share/wallpapers/4199401.jpg
wallpaper_dir = ~/.local/share/wallpapers
wallpaper_hook = ~/bin/wallpaper-changed.sh "$1"
wallpaper_search = off

idle_lock = 300
idle_dim = 120
dim_brightness = 10
idle_dpms = 330

lock_blur = 24
shell_opacity = 0.80

terminal = ghostty

menu = Browser,    zen
menu = Screenshot, grim -g "$(slurp)" - | wl-copy
